name: Build and Deploy Emscripten to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install emscripten
        run: |
          cd $HOME
          git clone --depth=1 https://github.com/emscripten-core/emsdk.git
          git fetch --tags
          git describe --tags `git rev-list --tags --max-count=1`
          git checkout $latest_tag
          cd $HOME/emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Build
        run: |
          source "$HOME/emsdk/emsdk_env.sh"
          cmake
          cmake --build
          mkdir -p _site
          mv build/out/* _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
